---
abstract: 'Control the output of a CGI Program'
author:
  - 'Nigel Horne <njh@bandsman.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Output
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Info: 0.1
  Compress::Zlib: 0
  IO::CaptureOutput: 0
  IO::String: 0
  MD5: 0
  Test::More: 0.82
version: 0.01
